resolver: lts-5.17
packages:
- '.'
- location:
    git: https://github.com/j-mueller/virtual-hom
    commit: 939b34d38d56e8b2d927055339ece0602525ed83

extra-deps:
- async-2.0.2

# Override default flag values for local packages and extra-deps
flags:
  iso-svg:
    examples: false

# Extra package databases containing global packages
extra-package-dbs: []

compiler: ghcjs-0.2.0.20160315_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20160315_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20160315/ghcjs-0.2.0.20160315.tar.gz"